[package]
name = "oxide"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Command-line interface for OxiRS - import, export, migration, and benchmarking tools"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
oxirs-core = { path = "../../core/oxirs-core" }
oxirs-fuseki = { path = "../../server/oxirs-fuseki" }
oxirs-gql = { path = "../../server/oxirs-gql" }
oxirs-tdb = { path = "../../storage/oxirs-tdb" }
clap.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rand = "0.8"
uuid = "1.11"       # UUID generation
sysinfo = "0.32"    # System information
tempfile = "3.8"    # Temporary file handling

# Enhanced CLI features
indicatif = "0.17"  # Progress bars
colored = "2.1"     # Colored output
prettytable-rs = "0.10"  # Table formatting
rustyline = "16.0"  # Interactive mode
rustyline-derive = "0.10"  # Helper derive macros
strsim = "0.11"     # String similarity for suggestions
atty = "0.2"        # Terminal detection
regex = "1.10"      # Pattern matching for validation
url = "2.5"         # URL parsing and validation
dirs = "5.0"        # Platform-specific directories
clap_complete = "4.5"  # Shell completion support
textwrap = "0.16"   # Text wrapping for help
unicode-width = "0.1"  # Unicode text width
terminal_size = "0.3"  # Terminal dimensions
shlex = "1.3"       # Shell-like parsing
ring = "0.17"       # Cryptography for secrets
chrono = { version = "0.4", features = ["serde"] }  # Date/time handling
dialoguer = "0.11"  # Interactive prompts

[dev-dependencies]
criterion.workspace = true
tokio-test = "0.4"

[features]
default = []
all-features = [
    "star",
    "ai", 
    "cluster",
    "text",
    "geo",
    "vec"
]
star = ["oxirs-star"]
ai = ["oxirs-chat"] # oxirs-embed temporarily disabled
cluster = ["oxirs-cluster"]
text = ["tantivy"]
geo = []
vec = ["oxirs-vec"]

[dependencies.oxirs-star]
path = "../../engine/oxirs-star"
optional = true

# [dependencies.oxirs-embed] # Temporarily disabled
# path = "../../ai/oxirs-embed"
# optional = true

[dependencies.oxirs-chat]
path = "../../ai/oxirs-chat"
optional = true

[dependencies.oxirs-cluster]
path = "../../storage/oxirs-cluster"
optional = true

[dependencies.oxirs-vec]
path = "../../engine/oxirs-vec"
optional = true

[dependencies.tantivy]
workspace = true
optional = true

[[bin]]
name = "oxide"
path = "src/main.rs"

