[package]
name = "oxirs-rule"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Forward/backward rule engine for RDFS, OWL, and SWRL reasoning"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
oxirs-core = { path = "../../core/oxirs-core" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
regex = "1.11"
tokio = { version = "1.45", features = ["fs", "io-util"] }
lazy_static = "1.5"
rand = "0.8"

[dev-dependencies]
criterion.workspace = true
tempfile = "3.14"
tokio = { version = "1.45", features = ["full"] }

[features]
default = ["rdfs"]
rdfs = []
owl = []
swrl = []

