[package]
name = "oxirs-federate"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "SERVICE planner and GraphQL stitching for federated SPARQL queries"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
oxirs-core = { path = "../../core/oxirs-core", features = ["serde"] }
oxirs-gql = { path = "../../server/oxirs-gql" }
oxirs-vec = { path = "../../engine/oxirs-vec" }
tokio.workspace = true
hyper.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
reqwest = { version = "0.12", features = ["json", "stream", "gzip", "brotli"] }
async-trait.workspace = true
futures.workspace = true
dashmap = "6.1"
parking_lot = "0.12"
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
url.workspace = true
backoff = { version = "0.4", features = ["tokio"] }
governor = "0.6"
tower = { workspace = true, features = ["limit", "load-shed", "buffer", "timeout"] }
tower-http = { workspace = true, features = ["cors", "trace", "timeout", "compression-gzip"] }
http = "1.1"
bytes = "1.8"
base64 = "0.22"
jsonwebtoken = "9.3"
rustls = { version = "0.23", features = ["std"] }
rustls-webpki = "0.102"
opentelemetry = { version = "0.30", features = ["trace", "metrics"], optional = true }
opentelemetry-jaeger = { version = "0.22", optional = true }
opentelemetry-otlp = { version = "0.30", optional = true }
prometheus = { version = "0.13", optional = true }
async-stream = "0.3"
pin-project = "1.1"
# oxigraph = "0.4.11"  # REMOVED: Using oxirs-core instead
nalgebra = { version = "0.33", features = ["serde"] }
async-graphql = { version = "7.0", optional = true }
async-graphql-parser = { version = "7.0", optional = true }
mdns-sd = { version = "0.11", optional = true }
kube = { version = "0.95", features = ["client", "config"], optional = true }
k8s-openapi = { version = "0.23", features = ["v1_29"], optional = true }
oauth2 = { version = "4.4", optional = true }
redis = { version = "0.27", features = ["aio", "tokio-comp"], optional = true }
lru = { version = "0.12", optional = true }
moka = { version = "0.12", features = ["future"], optional = true }
bloom = { version = "0.3", optional = true }
petgraph = "0.6"
regex = "1.11"
md5 = "0.7"
flate2 = "1.0"
brotli = "7.0"
lz4_flex = "0.11"
zstd = "0.13"
rmp-serde = "1.3"
serde_cbor = "0.11"
tokio-stream = { version = "0.1", features = ["sync"] }
futures-util = "0.3"
rand = "0.8.5"
rand_distr = "0.4"
ndarray = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tokio-test = "0.4"
mockito = "1.6"
wiremock = "0.6"
proptest = "1.5"
serial_test = "3.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = ["caching", "monitoring", "redis-cache"]
graphql-stitching = ["async-graphql", "async-graphql-parser"]
kubernetes = ["kube", "k8s-openapi"]
redis-cache = ["redis"]
caching = ["lru", "moka", "bloom"]
monitoring = ["opentelemetry", "opentelemetry-jaeger", "opentelemetry-otlp", "prometheus"]
service-discovery = ["mdns-sd"]
oauth = ["oauth2"]

