[package]
name = "oxirs-federate"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "SERVICE planner and GraphQL stitching for federated SPARQL queries"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
oxirs-core = { path = "../../core/oxirs-core" }
oxirs-gql = { path = "../../server/oxirs-gql" }
tokio = { version = "1.42", features = ["full"] }
hyper = { version = "1.6", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "2.0"
tracing = "0.1"
reqwest = { version = "0.12", features = ["json", "stream", "gzip", "brotli"] }
async-trait = "0.1"
futures = "0.3"
dashmap = "6.1"
parking_lot = "0.12"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.11", features = ["v4", "serde"] }
url = "2.5"
backoff = "0.4"
governor = "0.6"
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.6", features = ["cors", "trace", "timeout", "compression-gzip"] }
http = "1.1"
bytes = "1.8"
base64 = "0.22"
jsonwebtoken = "9.3"
rustls = { version = "0.23", features = ["std"] }
rustls-webpki = "0.102"
opentelemetry = { version = "0.22", features = ["trace", "metrics"], optional = true }
opentelemetry-jaeger = { version = "0.22", optional = true }
opentelemetry-otlp = { version = "0.22", optional = true }
prometheus = { version = "0.13", optional = true }
async-stream = "0.3"
pin-project = "1.1"
sparql-syntax = "0.3"
async-graphql = { version = "7.0", optional = true }
async-graphql-parser = { version = "7.0", optional = true }
mdns-sd = { version = "0.11", optional = true }
kube = { version = "0.95", features = ["client", "config"], optional = true }
k8s-openapi = { version = "0.23", features = ["v1_29"], optional = true }
oauth2 = "4.4"
redis = { version = "0.27", features = ["aio", "tokio-comp"], optional = true }
lru = { version = "0.12", optional = true }
moka = { version = "0.12", features = ["future"], optional = true }
bloom = { version = "0.3", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tokio-test = "0.4"
mockito = "1.6"
wiremock = "0.6"
proptest = "1.5"
serial_test = "3.1"

[features]
default = ["caching", "monitoring"]
graphql-stitching = ["async-graphql", "async-graphql-parser"]
kubernetes = ["kube", "k8s-openapi"]
redis-cache = ["redis"]
caching = ["lru", "moka", "bloom"]
monitoring = ["opentelemetry", "opentelemetry-jaeger", "opentelemetry-otlp", "prometheus"]
service-discovery = ["mdns-sd"]
oauth = ["oauth2"]

