[package]
name = "oxirs-federate"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "SERVICE planner and GraphQL stitching for federated SPARQL queries"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
oxirs-core = { path = "../../core/oxirs-core" }
oxirs-gql = { path = "../../server/oxirs-gql" }
tokio.workspace = true
hyper.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true

[features]
default = []
graphql-stitching = []

