[package]
name = "rust-refactor-split"
version = "0.1.0"
edition = "2021"

[workspace]
# This is a standalone tool, not part of the main workspace

[dependencies]
syn = { version = "2", features = ["full", "parsing", "printing", "visit"] }
quote = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
walkdir = "2"
prettyplease = "0.2"

[[bin]]
name = "rust-refactor-split"
path = "src/main.rs"
